### ISSUE TITLE
document how to setting "Exposing the marketplace" step by step 

### ISSUE THREAD

**Issue by jeffliao888** [coder/code-marketplace#14]
Is there any document to show how to setting "Exposing the marketplace" step by step  ?
because I try to use  TLS-terminating reverse proxy with NGINX and I meet so many problems.
If there are some documents or URL links to show how to setup step by step,  that will be great help for me, 

Thank you very much !

**Comment by jeffliao888** [comment]
Thank you very much for code-asher !
I had Exposing the marketplace already(use TLS-terminating reverse proxy with NGINX )

The following step by step to show how to set it up: 
1. Install NGINX: 
The first step is to install NGINX on CentOS server. You can do this by running the following command:
>sudo yum install nginx

2. Configure NGINX as a reverse proxy: Once NGINX is installed, you need to configure it as a reverse proxy. Open the NGINX configuration file /etc/nginx/nginx.conf in a text editor :
> vi /etc/nginx/nginx.conf  
#================================
and replace its content with the following:
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        server localhost:3001;
    }

    server {
        listen 80;
        server_name server_name.your_domain.com;

        return 301 https://$server_name$request_uri/;
    }

    server {
        listen 443 ssl;
        server_name server_name.your_domain.com;

        ssl_certificate /etc/nginx/certificate/nginx-certificate.crt;
        ssl_certificate_key /etc/nginx/certificate/nginx.key;

        location / {
            proxy_pass http://backend/;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
#================================

3. add the following mapping to your DNS server , IP address ->  server_name.your_domain.com
192.168.xxx.xxx   server_name.your_domain.com

4. Create certificate for TLS-

>mkdir /etc/nginx/certificate
>cd /etc/nginx/certificate
>openssl req -new -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out nginx-certificate.crt -keyout nginx.key

Country Name (2 letter code) [XX]: "Input your country code"
State or Province Name (full name) []: "Input your Province Name"
Locality Name (eg, city) [Default City]: "Input your City Name"
Organization Name (eg, company) [Default Company Ltd]: "Input your Company Name"
Organizational Unit Name (eg, section) []:
Common Name (eg, your name or your server's hostname) []: server_name.your_domain.com
Email Address []:

5. Restart NGINX service with the following command:
> systemctl restart nginx

6. Open a brower(Firefox or Chrome) for input  https://server_name.your_domain.com/ , if you can see the Output messages “Marketplace is running” from the brower , it worked !

**Comment by code-asher** [comment]
Glad you got it working and thank you for posting the steps!  I added a wiki page based on the information you provided.  https://github.com/coder/code-marketplace/wiki/NGINX
