### ISSUE TITLE
💪 Support multi-platform packages

### ISSUE THREAD

**Issue by bdsoha** [coder/code-marketplace#20]
### Description

The release of `code-marketplace` includes a version designated for ARM architectures. 
However, the actual service does not differentiate between architectures.

### Example

The [`redhat.java`](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension is architecture specific.
There are separate downloads available for each architecture.
When attempting to upload various architectures to `code-marketplace`, only the universal or *Linux x64* is actually uploaded.

**Comment by bpmct** [comment]
Modifying this to support other operating systems as well!
