### ISSUE TITLE
Incorrect capture groups during removal

### ISSUE THREAD

**Issue by podedra92** [coder/code-marketplace#23]
### Description
Some packages do not adhere to the expected convention during remove.
We are expected to pass `publisher.extension-1.0.0` or `publisher.extension`  [ParseExtensionID ](https://github.com/coder/code-marketplace/blob/main/storage/storage.go#L259) uses regex capture groups to split this string or "_id_"

May be better placed just to pass in Publisher/extension/version (optional) as seperate args.
Or introduce a breaking change like using a different char maybe `+` to replace `-` for version identifier

### Example Extensions
- [docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker) 
- [jupyter-renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers)
- [python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)

**Comment by code-asher** [comment]
Thank you for the report!

I think maybe we change this to `@`, the `-` was initially done to match VS Code but I think there was a misunderstanding as VS Code actually uses `@` (maybe they ran into the same bug and changed it).
