### ISSUE TITLE
Publish to `artifacthub`

### ISSUE THREAD

**Issue by bdsoha** [coder/code-marketplace#25]
Any plans to publish the HELM chart to artifacthub.io ?

**Comment by code-asher** [comment]
No plans at the moment, but if it is something we can automate 
when we publish then it seems reasonable to me.

**Comment by bdsoha** [comment]
Coder already has an existing account on *ArtifactHUB* and a chart for *Coder*:

- **Repository:** https://helm.coder.com/v2
- **ArtifactHUB:** https://artifacthub.io/packages/helm/coder-v2/coder

I would expect other coder related resources also be published:

- **Code Server:** https://github.com/coder/code-server/blob/main/docs/helm.md
- **Code Marketplace:** https://github.com/coder/code-marketplace/blob/main/helm/README.md

**Comment by bdsoha** [comment]
Closing in place of https://github.com/coder/coder/issues/9066 .
