### ISSUE TITLE
document how to use with VS Code and VS Codium

### ISSUE THREAD

**Issue by bpmct** [coder/code-marketplace#3]
VS Code docs example: https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code

VS Codium docs example: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace

**Comment by jonathanalgar** [comment]
> VS Code docs example: https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code
> 
> VS Codium docs example: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace

Thanks. Suggest to surface these links to the body of the README.
