### ISSUE TITLE
Check for Updates results in "Invalid page size"

### ISSUE THREAD

**Issue by mayrholu** [coder/code-marketplace#38]
Hi there,

I have a problem: 
If I hit "Check for Extension Updates" in VSCode I get "All extensions up to date" which is definitely false as I just uploaded some new versions.
The developer tools' network section shows the following response for the update request:
```
{
    "message": "Invalid page size",
    "detail": "Check that the page size is between zero and fifty",
    "requestId": "806226fe-9b68-4cb3-b8bc-7ee1f50f48fc"
}{
...
```
Apparently VSCode requests a page size of 74 (the total count of extensions?). 

Is there a way to increase the maximum page size? Or can I fix that issue myself?

Thank you in advance!

**Comment by code-asher** [comment]
Oh interesting.  The maximum page size is currently hardcoded, but we should make it configurable, maybe with a `--max-page-size` flag?  And we could make it so if you set `0` then you can have any page size, maybe.

Definitely happy to merge a PR if you want to add this.

**Comment by mayrholu** [comment]
Unfortunately I don't know Go. I could increase the hardcoded limit but I have no idea how to add a flag. 

@code-asher Any chance you could implement this fix?

**Comment by code-asher** [comment]
I can add it to our backlog, but I am not sure it will get picked up soon.

**Comment by bcpeinhardt** [comment]
Hey there!

We've added a flag `--max-page-size` to override the limit, and updated the default limit from 50 to 200, so the next release should fix this issue for you 😄

**Comment by mayrholu** [comment]
Nice! Thanks a lot :)
