### ISSUE TITLE
Did it apply to code-server?

### ISSUE THREAD

**Issue by zWingz** [coder/code-marketplace#7]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/13031838/203501184-2491ddf5-9aeb-4d66-a88a-16dc557872d9.png">

**Comment by code-asher** [comment]
Sorry I missed this.  This marketplace can be used with code-server.  [Let me know if you need help configuring](https://github.com/coder/code-marketplace#usage-in-code-server)

Looks like your code-server is still using the default Open VSX.

**Comment by zWingz** [comment]
@code-asher I start the server by `code-server`.  Doesn't is the default marketplace at code-server ?
