### ISSUE TITLE
How to upload to Artifactory for use by code-server

### ISSUE THREAD

**Issue by Jose-Matsuda** [coder/code-marketplace#72]
I don't think there's documentation for this but for reference I'm in a locked-down k8s cluster serving jupyter notebooks with code-server pointing to a running code-marketplace pod for extensions. Just so users could install extensions asap, we baked in some default extensions into the built `code-marketplace` image but are now looking to not have to do that. We do have Jfrog Artifactory running and pushing extensions to a local artifactory repo would be much easier.

I know @janLo was able to do this, if you could share what you did with your artifactory that would be amazing :)

**Comment by code-asher** [comment]
Back when I was last testing, I would use `code-marketplace add` itself for this.  So:

```
export ARTIFACTORY_TOKEN="my-token"
./code-marketplace add --artifactory http://artifactory.server/artifactory --repo extensions [extension to add]
```

**Comment by Jose-Matsuda** [comment]
> Back when I was last testing, I would use `code-marketplace add` for this. So:
> 
> ```
> export ARTIFACTORY_TOKEN="my-token"
> ./code-marketplace add --artifactory http://artifactory.server/artifactory --repo extensions [extension to add]
> ```
> 
> Or, if you want to take the existing extensions you had in the image, you can just copy them exactly as they are into the Artifactory repo.

Would that just be putting the .vsix files at any level in say a [generic local repository](https://jfrog.com/blog/5-special-repositories-in-artifactory-you-should-know-about/)?

**Comment by code-asher** [comment]
Sorry for the delay.  Yup it should work in a generic repository, I think this is what I used back when I last tested.

**Comment by code-asher** [comment]
I think also any level will work, just need to make sure you put the base in the flag, so `--repo foo/bar/extensions`.  I think this should work, but I also think I only tested them at the root of the repository, so I cannot be sure.

**Comment by code-asher** [comment]
Ah wait one more thing, it is not just putting the `.vsix` files in a repository.  The marketplace requires that the extension be extracted and put in a specific directory structure, and that the `.vsix` file also exist (this is for performance reasons).  That is why I recommend using the `add` command since it does that for you, but you could manually create the expected directory structure and extract the `.vsix`.

**Comment by Jose-Matsuda** [comment]
Ah I see, yeah trying something that I thought would be ok from looking [here](https://github.com/coder/code-marketplace/blob/3e808a63c6894102d1c6d879e54344225aa96efe/storage/artifactory.go#L363) 
![Image](https://github.com/user-attachments/assets/4423964b-48e5-4dbf-9600-6954e7c56f64)


does at least produce an error message for me
![Image](https://github.com/user-attachments/assets/b7a6fbe0-fe1b-4b32-965c-26f3c3b5573a)


The file structure must be off, could you let me know what it _should_ look like? I was trying to gather the relevant info from the [open-vsx page](https://open-vsx.org/extension/eamodio/gitlens/15.6.2) but I'm not too sure what it should be

**Comment by code-asher** [comment]
We used to document the structure but removed the documentation because it was much easier to use `add`.

But you have the right directory structure, you just need to *also* extract the `.vsix` into that directory.  Here is an example of what it should look like (the structure is the same for a local dir and Artifactory):

```bash
λ ./code-marketplace --extensions-dir ./extensions add https://open-vsx.org/api/eamodio/gitlens/2024.11.2511/file/eamodio.gitlens-2024.11.2511.vsix
Unpacked eamodio.gitlens@2024.11.2511 to /home/coder/src/marketplace/extensions/eamodio/gitlens/2024.11.2511
  - eamodio.gitlens@2024.11.2511 has 0 dependencies
  - eamodio.gitlens@2024.11.2511 is not in a pack
λ tree ./extensions -L 4
./extensions # this will be vscode-extensions-local in your case
└── eamodio
    └── gitlens
        └── 2024.11.2511
            ├── [Content_Types].xml
            ├── eamodio.gitlens-2024.11.2511.vsix
            ├── extension
            └── extension.vsixmanifest
```

Hope that helps!
